name: Deploy Storybook to Vercel

on:
  push:
    branches: [storybook-deploy]

jobs:
  deploy:
    name: Trigger Vercel Storybook Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          curl -X POST "${{ secrets.VERCEL_STORYBOOK_DEPLOY_HOOK }}"
